import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { shadesOfPurple } from '@clerk/themes'
import { ThemeProvider } from "@/components/theme-provider";
import { Oxanium } from "next/font/google";




// Importing the fonts with custom variables

const OxaniumFont = Oxanium({
  subsets:['latin'],
  weight:"400"
})

// Metadata for the page (this can be dynamic as needed)
export const metadata: Metadata = {
  title: "Create Next App",  // Customize your title as needed
  description: "Generated by create next app",  // You can update this for SEO or dynamic content
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
      appearance={{
        baseTheme: shadesOfPurple,
        signIn: { baseTheme: shadesOfPurple },  // Example: separate theme for the sign-in form
      }}>
      <html lang="en" suppressHydrationWarning >
        <body
          className={`${OxaniumFont.className} antialiased`}
        >
           <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
